## パラメータの後のコメントはサポートされていません。
## オプションと値の間に余分なスペースを入れることはできません。
## https://mpv.io/manual/master/#positioning

toggle_align_to_cursor=no
# アライメントカーソルがパンするためにマウスボタンを押し続ける必要があるかどうか。no の場合 ドラッグしてパンする。yesの場合、1回目のクリックでパンするカーソルに追従し、2回目のクリックで無効になる。デフォルト no
suppress_osd=no
# スクリプトコマンドcursor-centric-zoomを使用するときに、OSDが属性video-zoomの新しい値を出力しないかどうか。デフォルトはno

#remember_position=yes